services:
  website:
    build:
      context: .
      dockerfile: docker/website/Dockerfile
    container_name: nextjs-website-container  
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network  # Updated network name for consistency

  flask-service:
    image: coolcraft71/python_backend:latest
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: python-server-container
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    networks:
      - app_network
    volumes:
      - .:/app
    restart: always
    command: ["python", "api_server.py"]

networks:
  app_network:  # Updated network name to make it tutorial-friendly
    driver: bridge